---
# author: Bryan

#- name: restart on Centos6
- name: "restart | restart node_exporter on Centos6"
  service: name=node_exporter enabled=yes state=restarted
  when: ansible_distribution_major_version=="6"

#- name: restart on Centos7
- name: "restart | restart node_exporter.service on Centos7"
  systemd: name=node_exporter.service enabled=yes state=restarted
  when: ansible_distribution_major_version=="7"
