---
# author: Bryan

- name: "install | disable chattr -i"
  shell: "chattr -i /etc/passwd* && chattr -i /etc/group* && chattr -i /etc/shadow*"

- name: "install | Create {{ group_name }} group."
  group: name={{ group_name }}

- name: "install | Create {{ user_name }} user."
  user: name={{ user_name }} group={{ group_name }} shell=/sbin/nologin

- name: "install | enable chattr +i"
  shell: "chattr +i /etc/passwd* && chattr +i /etc/group* && chattr +i /etc/shadow*"

- name: "install | Install daemonize"
  yum: name=daemonize state=present

- name: "install | mkdir {{ deploy_file_workpath }} directory"
  #shell: mkdir -p /usr/local/prometheus/node_exporter/
  file: path={{ deploy_file_workpath }} state=directory recurse=yes owner={{ user_name }} group={{ group_name }} mode=0755

- name: "install | unarchive node_exporter-0.17.0.linux-amd64.tar.gz"
  unarchive:
    src: "node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: /tmp
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
    copy: yes

- name: "install | copy node_exporter to {{ deploy_file_workpath }}"
  #shell: "cp /tmp/node_exporter-0.17.0.linux-amd64/node_exporter /usr/local/prometheus/node_exporter/"
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    #dest: /usr/local/prometheus/node_exporter/node_exporter
    dest: "{{ deploy_file_workpath }}/{{ deploy_file }}"
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
    remote_src: yes  #no表示src文件在本机上，yes表示src在远程主机上

- name: "install | daemon-reload node_exporter config"
  shell: systemctl daemon-reload
  when:  ansible_distribution_major_version=="7"

- name: "install | config node_exporter to Centos6"
  template: src=files/node_exporter.conf.c6.j2 dest=/etc/sysconfig/node_exporter.conf mode=0655 remote_src=no
  when: ansible_distribution_major_version=="6"
  #notify: restart on Centos6
  notify: "restart | restart node_exporter on Centos6"
  
- name: "install | install node_exporter to Centos6"
  template: src=files/node_exporter.c6.j2 dest=/etc/init.d/node_exporter mode=0655
  when: ansible_distribution_major_version=="6"
  #notify: restart on Centos6
  notify: "restart | restart node_exporter on Centos6"

- name: "install | install node_exporter.service to Centos7"
  template: src=files/node_exporter.service.c7.j2 dest=/usr/lib/systemd/system/node_exporter.service mode=0755
  when: ansible_distribution_major_version=="7"
  notify: 
  # - restart on Centos7
   - "restart | restart node_exporter.service on Centos7"
