---
# author: Bryan

- name: "install | disable chattr -i"
  shell: "chattr -i /etc/passwd* && chattr -i /etc/group* && chattr -i /etc/shadow*"

- name: "install | Create {{ group_name }} group."
  group: name={{ group_name }}

- name: "install | Create {{ user_name }} user."
  user: name={{ user_name }} group={{ group_name }} shell=/sbin/nologin

- name: "install | enable chattr +i"
  shell: "chattr +i /etc/passwd* && chattr +i /etc/group* && chattr +i /etc/shadow*"

- name: "install | Install daemonize"
  yum: name=daemonize state=present

- name: "install | mkdir node_exporter directory"
  #shell: mkdir -p /usr/local/prometheus/node_exporter/
  file: path=/usr/local/prometheus/node_exporter/ state=directory recurse=yes owner={{ user_name }} group={{ group_name }} mode=0755

- name: "install | unarchive node_exporter-0.17.0.linux-amd64.tar.gz"
  unarchive:
    src: "node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: /tmp
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
    copy: yes

- name: "install | copy node_exporter to /usr/local/prometheus/node_exporter/"
  #shell: "cp /tmp/node_exporter-0.17.0.linux-amd64/node_exporter /usr/local/prometheus/node_exporter/"
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/prometheus/node_exporter/node_exporter
    owner: "prometheus"
    group: "prometheus"
    mode: 0755

- name: "install | daemon-reload node_exporter config"
  shell: systemctl daemon-reload
  when:  ansible_distribution_major_version=="7"

- name: "install | install node_exporter to Centos6"
  template: src=files/node_exporter.c6.j2 dest=/etc/init.d/node_exporter
  when: ansible_distribution_major_version=="6"
  #notify: restart on Centos6
  notify: "restart | restart node_exporter on Centos6"

- name: "install | install node_exporter.service to Centos7"
  template: src=files/node_exporter.service.c7.j2 dest=/usr/lib/systemd/system/node_exporter.service
  when: ansible_distribution_major_version=="7"
  notify: 
  # - restart on Centos7
   - "restart | restart node_exporter.service on Centos7"

- name: "install | start node_exporter on Centos6"
  service: name=node_exporter state=started enabled=true
  when: ansible_distribution_major_version=="6"

- name: "install | start node_exporter.service on Centos7"
  service: name=node_exporter.service state=started enabled=true
  when: ansible_distribution_major_version=="7"
