---
# author: Bryan

- name: "uninstall | disable chattr -i"
  shell: "chattr -i /etc/passwd* && chattr -i /etc/group* && chattr -i /etc/shadow*"

- name: "uninstall | Remove {{ user_name }} user."
  user: name={{ user_name }} state=absent
  #user: name={{ user_name }} state=absent remove=yes   会删除家目录

- name: "uninstall | Remove {{ group_name }} group."
  group: name={{ group_name }} state=absent

- name: "uninstall | enable chattr +i"
  shell: "chattr +i /etc/passwd* && chattr +i /etc/group* && chattr +i /etc/shadow*"

- name: uninstall | Remove daemonize
  yum: name=daemonize state=removed
